# This is the docker for the flask server NOT FOR ODOO
version: '3.8'
services:
    api-service:
        build: ./flask_server/
        volumes:
            - ./flask_server/:/usr/src/app/
        ports:
            - 5001:5000
        environment:
            PORT: 5000
            FLASK_DEBUG: 1
