# This is the docker for the flask server NOT FOR ODOO
version: '3.10'
services:
  app:
    build:
      context: ./flask_server/
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - ./flask_server/:/usr/src/app/
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - FLASK_DEBUG=1
