version: '2'
services:
  web:
    platform: linux/x86_64
    image: odoo:16
    command: odoo --stop-after-init -d test -i odoo_llm_auto_responder
    user: "root:root"
    cpus: 4
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ../addons:/mnt/extra-addons
    depends_on:
      - db
    ports:
      - "8069:8069"
  db:
    platform: linux/x86_64
    image: postgres:12
    cpus: 2
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
#    command: ["postgres", "-c", "log_statement=all"]
volumes:
  odoo-web-data:
  odoo-db-data:
